package model;

// Generated 24/07/2015 07:24:43 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CotacaoMaterial generated by hbm2java
 */
@Entity
@Table(name = "cotacao_material", catalog = "sistema_gestao")
public class CotacaoMaterial implements java.io.Serializable {

	private Integer idcotacao;
	private String responsavel;
	private Date data;
	private Set<FornecimentoMaterial> fornecimentoMaterials = new HashSet<FornecimentoMaterial>(
			0);
	private Set<Material> materials = new HashSet<Material>(0);

	public CotacaoMaterial() {
	}

	public CotacaoMaterial(String responsavel, Date data,
			Set<FornecimentoMaterial> fornecimentoMaterials,
			Set<Material> materials) {
		this.responsavel = responsavel;
		this.data = data;
		this.fornecimentoMaterials = fornecimentoMaterials;
		this.materials = materials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcotacao", unique = true, nullable = false)
	public Integer getIdcotacao() {
		return this.idcotacao;
	}

	public void setIdcotacao(Integer idcotacao) {
		this.idcotacao = idcotacao;
	}

	@Column(name = "responsavel")
	public String getResponsavel() {
		return this.responsavel;
	}

	public void setResponsavel(String responsavel) {
		this.responsavel = responsavel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotacaoMaterial")
	public Set<FornecimentoMaterial> getFornecimentoMaterials() {
		return this.fornecimentoMaterials;
	}

	public void setFornecimentoMaterials(
			Set<FornecimentoMaterial> fornecimentoMaterials) {
		this.fornecimentoMaterials = fornecimentoMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotacaoMaterial")
	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
