package model;

// Generated 24/07/2015 07:24:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FornecimentoFerramentaId generated by hbm2java
 */
@Embeddable
public class FornecimentoFerramentaId implements java.io.Serializable {

	private long idfornecimentoFerramenta;
	private long cotacaoFerramentaIdcotacao;

	public FornecimentoFerramentaId() {
	}

	public FornecimentoFerramentaId(long idfornecimentoFerramenta,
			long cotacaoFerramentaIdcotacao) {
		this.idfornecimentoFerramenta = idfornecimentoFerramenta;
		this.cotacaoFerramentaIdcotacao = cotacaoFerramentaIdcotacao;
	}

	@Column(name = "idfornecimento_ferramenta", nullable = false)
	public long getIdfornecimentoFerramenta() {
		return this.idfornecimentoFerramenta;
	}

	public void setIdfornecimentoFerramenta(long idfornecimentoFerramenta) {
		this.idfornecimentoFerramenta = idfornecimentoFerramenta;
	}

	@Column(name = "cotacao_ferramenta_idcotacao", nullable = false)
	public long getCotacaoFerramentaIdcotacao() {
		return this.cotacaoFerramentaIdcotacao;
	}

	public void setCotacaoFerramentaIdcotacao(long cotacaoFerramentaIdcotacao) {
		this.cotacaoFerramentaIdcotacao = cotacaoFerramentaIdcotacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FornecimentoFerramentaId))
			return false;
		FornecimentoFerramentaId castOther = (FornecimentoFerramentaId) other;

		return (this.getIdfornecimentoFerramenta() == castOther
				.getIdfornecimentoFerramenta())
				&& (this.getCotacaoFerramentaIdcotacao() == castOther
						.getCotacaoFerramentaIdcotacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdfornecimentoFerramenta();
		result = 37 * result + (int) this.getCotacaoFerramentaIdcotacao();
		return result;
	}

}
