package model;

// Generated 24/07/2015 07:24:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FornecimentoMaterialId generated by hbm2java
 */
@Embeddable
public class FornecimentoMaterialId implements java.io.Serializable {

	private int idfornecimentoMaterial;
	private int cotacaoMaterialIdcotacao;

	public FornecimentoMaterialId() {
	}

	public FornecimentoMaterialId(int idfornecimentoMaterial,
			int cotacaoMaterialIdcotacao) {
		this.idfornecimentoMaterial = idfornecimentoMaterial;
		this.cotacaoMaterialIdcotacao = cotacaoMaterialIdcotacao;
	}

	@Column(name = "idfornecimento_material", nullable = false)
	public int getIdfornecimentoMaterial() {
		return this.idfornecimentoMaterial;
	}

	public void setIdfornecimentoMaterial(int idfornecimentoMaterial) {
		this.idfornecimentoMaterial = idfornecimentoMaterial;
	}

	@Column(name = "cotacao_material_idcotacao", nullable = false)
	public int getCotacaoMaterialIdcotacao() {
		return this.cotacaoMaterialIdcotacao;
	}

	public void setCotacaoMaterialIdcotacao(int cotacaoMaterialIdcotacao) {
		this.cotacaoMaterialIdcotacao = cotacaoMaterialIdcotacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FornecimentoMaterialId))
			return false;
		FornecimentoMaterialId castOther = (FornecimentoMaterialId) other;

		return (this.getIdfornecimentoMaterial() == castOther
				.getIdfornecimentoMaterial())
				&& (this.getCotacaoMaterialIdcotacao() == castOther
						.getCotacaoMaterialIdcotacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfornecimentoMaterial();
		result = 37 * result + this.getCotacaoMaterialIdcotacao();
		return result;
	}

}
