package model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MontagemId generated by hbm2java
 */
@Embeddable
public class MontagemId implements java.io.Serializable {

	private long idmontagem;
	private long conjuntoIdconjunto;

	public MontagemId() {
	}

	public MontagemId(long idmontagem, long conjuntoIdconjunto) {
		this.idmontagem = idmontagem;
		this.conjuntoIdconjunto = conjuntoIdconjunto;
	}

	@Column(name = "idmontagem", nullable = false)
	public long getIdmontagem() {
		return this.idmontagem;
	}

	public void setIdmontagem(long idmontagem) {
		this.idmontagem = idmontagem;
	}

	@Column(name = "conjunto_idconjunto", nullable = false)
	public long getConjuntoIdconjunto() {
		return this.conjuntoIdconjunto;
	}

	public void setConjuntoIdconjunto(long conjuntoIdconjunto) {
		this.conjuntoIdconjunto = conjuntoIdconjunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MontagemId))
			return false;
		MontagemId castOther = (MontagemId) other;

		return (this.getIdmontagem() == castOther.getIdmontagem())
				&& (this.getConjuntoIdconjunto() == castOther
						.getConjuntoIdconjunto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdmontagem();
		result = 37 * result + (int) this.getConjuntoIdconjunto();
		return result;
	}

}
