package model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pfmea generated by hbm2java
 */
@Entity
@Table(name = "pfmea", catalog = "sistema_gestao")
public class Pfmea implements java.io.Serializable {

	private PfmeaId id;
	private RiskAssesment riskAssesment;
	private String responsavel;
	private String link;

	public Pfmea() {
	}

	public Pfmea(PfmeaId id, RiskAssesment riskAssesment) {
		this.id = id;
		this.riskAssesment = riskAssesment;
	}

	public Pfmea(PfmeaId id, RiskAssesment riskAssesment, String responsavel,
			String link) {
		this.id = id;
		this.riskAssesment = riskAssesment;
		this.responsavel = responsavel;
		this.link = link;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPfmea", column = @Column(name = "id_pfmea", nullable = false)),
			@AttributeOverride(name = "riskAssesmentIdRiskAssesment", column = @Column(name = "risk_assesment_id_risk_assesment", nullable = false)),
			@AttributeOverride(name = "riskAssesmentConjuntoIdconjunto", column = @Column(name = "risk_assesment_conjunto_idconjunto", nullable = false)) })
	public PfmeaId getId() {
		return this.id;
	}

	public void setId(PfmeaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "risk_assesment_id_risk_assesment", referencedColumnName = "id_risk_assesment", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "risk_assesment_conjunto_idconjunto", referencedColumnName = "conjunto_idconjunto", nullable = false, insertable = false, updatable = false) })
	public RiskAssesment getRiskAssesment() {
		return this.riskAssesment;
	}

	public void setRiskAssesment(RiskAssesment riskAssesment) {
		this.riskAssesment = riskAssesment;
	}

	@Column(name = "responsavel")
	public String getResponsavel() {
		return this.responsavel;
	}

	public void setResponsavel(String responsavel) {
		this.responsavel = responsavel;
	}

	@Column(name = "link")
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
