package model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RiskAssesment generated by hbm2java
 */
@Entity
@Table(name = "risk_assesment", catalog = "sistema_gestao")
public class RiskAssesment implements java.io.Serializable {

	private RiskAssesmentId id;
	private Conjunto conjunto;
	private String riskAssesmentcol;
	private Set<Pfmea> pfmeas = new HashSet<Pfmea>(0);

	public RiskAssesment() {
	}

	public RiskAssesment(RiskAssesmentId id, Conjunto conjunto) {
		this.id = id;
		this.conjunto = conjunto;
	}

	public RiskAssesment(RiskAssesmentId id, Conjunto conjunto,
			String riskAssesmentcol, Set<Pfmea> pfmeas) {
		this.id = id;
		this.conjunto = conjunto;
		this.riskAssesmentcol = riskAssesmentcol;
		this.pfmeas = pfmeas;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idRiskAssesment", column = @Column(name = "id_risk_assesment", nullable = false)),
			@AttributeOverride(name = "conjuntoIdconjunto", column = @Column(name = "conjunto_idconjunto", nullable = false)) })
	public RiskAssesmentId getId() {
		return this.id;
	}

	public void setId(RiskAssesmentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "conjunto_idconjunto", nullable = false, insertable = false, updatable = false)
	public Conjunto getConjunto() {
		return this.conjunto;
	}

	public void setConjunto(Conjunto conjunto) {
		this.conjunto = conjunto;
	}

	@Column(name = "risk_assesmentcol")
	public String getRiskAssesmentcol() {
		return this.riskAssesmentcol;
	}

	public void setRiskAssesmentcol(String riskAssesmentcol) {
		this.riskAssesmentcol = riskAssesmentcol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "riskAssesment")
	public Set<Pfmea> getPfmeas() {
		return this.pfmeas;
	}

	public void setPfmeas(Set<Pfmea> pfmeas) {
		this.pfmeas = pfmeas;
	}

}
