package br.com.synergy.model;

// Generated 06/08/2015 08:46:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraPeca generated by hbm2java
 */
@Entity
@Table(name = "compra_peca", catalog = "sistema_gestao")
public class CompraPeca implements java.io.Serializable {

	private Long idfornecimentoPeca;
	private Peca peca;
	private Pep pep;
	private Boolean okPrazo;
	private Boolean okEspec;
	private Boolean okVisita;
	private Boolean okAssist;
	private Date dataAquisicao;
	private Double preco;

	public CompraPeca() {
	}

	public CompraPeca(Peca peca, Pep pep) {
		this.peca = peca;
		this.pep = pep;
	}

	public CompraPeca(Peca peca, Pep pep, Boolean okPrazo, Boolean okEspec,
			Boolean okVisita, Boolean okAssist, Date dataAquisicao, Double preco) {
		this.peca = peca;
		this.pep = pep;
		this.okPrazo = okPrazo;
		this.okEspec = okEspec;
		this.okVisita = okVisita;
		this.okAssist = okAssist;
		this.dataAquisicao = dataAquisicao;
		this.preco = preco;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idfornecimento_peca", unique = true, nullable = false)
	public Long getIdfornecimentoPeca() {
		return this.idfornecimentoPeca;
	}

	public void setIdfornecimentoPeca(Long idfornecimentoPeca) {
		this.idfornecimentoPeca = idfornecimentoPeca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_idpeca", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "pep_idpep", referencedColumnName = "idpep", nullable = false),
			@JoinColumn(name = "pep_Conta_idConta", referencedColumnName = "Conta_idConta", nullable = false) })
	public Pep getPep() {
		return this.pep;
	}

	public void setPep(Pep pep) {
		this.pep = pep;
	}

	@Column(name = "ok_prazo")
	public Boolean getOkPrazo() {
		return this.okPrazo;
	}

	public void setOkPrazo(Boolean okPrazo) {
		this.okPrazo = okPrazo;
	}

	@Column(name = "ok_espec")
	public Boolean getOkEspec() {
		return this.okEspec;
	}

	public void setOkEspec(Boolean okEspec) {
		this.okEspec = okEspec;
	}

	@Column(name = "ok_visita")
	public Boolean getOkVisita() {
		return this.okVisita;
	}

	public void setOkVisita(Boolean okVisita) {
		this.okVisita = okVisita;
	}

	@Column(name = "ok_assist")
	public Boolean getOkAssist() {
		return this.okAssist;
	}

	public void setOkAssist(Boolean okAssist) {
		this.okAssist = okAssist;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_aquisicao", length = 10)
	public Date getDataAquisicao() {
		return this.dataAquisicao;
	}

	public void setDataAquisicao(Date dataAquisicao) {
		this.dataAquisicao = dataAquisicao;
	}

	@Column(name = "preco", precision = 22, scale = 0)
	public Double getPreco() {
		return this.preco;
	}

	public void setPreco(Double preco) {
		this.preco = preco;
	}

}
