package br.com.synergy.model;

// Generated 25/07/2015 13:37:07 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * CotacaoFerramenta generated by hbm2java
 */
@Entity
@Table(name = "cotacao_ferramenta", catalog = "sistema_gestao")
public class CotacaoFerramenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idcotacao;
	private Date data;
	private String responsavel;
	private String descricao;
	private Set<Ferramenta> ferramentas = new HashSet<Ferramenta>(0);
	private Set<FornecimentoFerramenta> fornecimentoFerramentas = new HashSet<FornecimentoFerramenta>(
			0);
	private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);

	public CotacaoFerramenta() {
	}

	public CotacaoFerramenta(Date data, String responsavel,
			Set<Ferramenta> ferramentas,
			Set<FornecimentoFerramenta> fornecimentoFerramentas,
			Set<Fornecedor> fornecedors) {
		this.data = data;
		this.responsavel = responsavel;
		this.ferramentas = ferramentas;
		this.fornecimentoFerramentas = fornecimentoFerramentas;
		this.fornecedors = fornecedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcotacao", unique = true, nullable = false)
	public Long getIdcotacao() {
		return this.idcotacao;
	}

	public void setIdcotacao(Long idcotacao) {
		this.idcotacao = idcotacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "responsavel")
	public String getResponsavel() {
		return this.responsavel;
	}

	public void setResponsavel(String responsavel) {
		this.responsavel = responsavel;
	}
	
	@NotNull
	@Column(name = "descricao")
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotacaoFerramenta")
	public Set<Ferramenta> getFerramentas() {
		return this.ferramentas;
	}

	public void setFerramentas(Set<Ferramenta> ferramentas) {
		this.ferramentas = ferramentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotacaoFerramenta")
	public Set<FornecimentoFerramenta> getFornecimentoFerramentas() {
		return this.fornecimentoFerramentas;
	}

	public void setFornecimentoFerramentas(
			Set<FornecimentoFerramenta> fornecimentoFerramentas) {
		this.fornecimentoFerramentas = fornecimentoFerramentas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "cotacao_ferramenta_has_fornecedor", catalog = "sistema_gestao", joinColumns = { @JoinColumn(name = "cotacao_ferramenta_idcotacao", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "fornecedor_idfornecedor", nullable = false, updatable = false) })
	public Set<Fornecedor> getFornecedors() {
		return this.fornecedors;
	}

	public void setFornecedors(Set<Fornecedor> fornecedors) {
		this.fornecedors = fornecedors;
	}

}
