package br.com.synergy.model;

// Generated 24/07/2015 08:08:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", catalog = "sistema_gestao")
public class Endereco implements java.io.Serializable {

	private Long idendereco;
	private String logradouro;
	private String numero;
	private String bairro;
	private String cep;
	private String estado;
	private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);

	public Endereco() {
	}

	public Endereco(String logradouro, String numero, String bairro,
			String cep, String estado, Set<Fornecedor> fornecedors) {
		this.logradouro = logradouro;
		this.numero = numero;
		this.bairro = bairro;
		this.cep = cep;
		this.estado = estado;
		this.fornecedors = fornecedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idendereco", unique = true, nullable = false)
	public Long getIdendereco() {
		return this.idendereco;
	}

	public void setIdendereco(Long idendereco) {
		this.idendereco = idendereco;
	}

	@Column(name = "logradouro")
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero", length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "bairro")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cep", length = 8)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Fornecedor> getFornecedors() {
		return this.fornecedors;
	}

	public void setFornecedors(Set<Fornecedor> fornecedors) {
		this.fornecedors = fornecedors;
	}

}
