package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ferramenta generated by hbm2java
 */
@Entity
@Table(name = "ferramenta", catalog = "sistema_gestao")
public class Ferramenta implements java.io.Serializable {

	private Long idferramenta;
	private String idEquipament;
	private String nome;
	private Double length;
	private Double height;
	private Double width;
	private Double partPerHour;
	private String utilidade;
	private Integer cycle;
	private Double areaStack;
	private Double area;
	private Integer maxStack;
	private String descricao;
	private Set<ParticipanteFerramenta> participanteFerramentas = new HashSet<ParticipanteFerramenta>(
			0);
	private Set<Montagem> montagems = new HashSet<Montagem>(0);
	private Set<CompraFerramenta> compraFerramentas = new HashSet<CompraFerramenta>(
			0);

	public Ferramenta() {
	}

	public Ferramenta(String idEquipament) {
		this.idEquipament = idEquipament;
	}

	public Ferramenta(String idEquipament, String nome, Double length,
			Double height, Double width, Double partPerHour, String utilidade,
			Integer cycle, Double areaStack, Double area, Integer maxStack,
			String descricao,
			Set<ParticipanteFerramenta> participanteFerramentas,
			Set<Montagem> montagems, Set<CompraFerramenta> compraFerramentas) {
		this.idEquipament = idEquipament;
		this.nome = nome;
		this.length = length;
		this.height = height;
		this.width = width;
		this.partPerHour = partPerHour;
		this.utilidade = utilidade;
		this.cycle = cycle;
		this.areaStack = areaStack;
		this.area = area;
		this.maxStack = maxStack;
		this.descricao = descricao;
		this.participanteFerramentas = participanteFerramentas;
		this.montagems = montagems;
		this.compraFerramentas = compraFerramentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idferramenta", unique = true, nullable = false)
	public Long getIdferramenta() {
		return this.idferramenta;
	}

	public void setIdferramenta(Long idferramenta) {
		this.idferramenta = idferramenta;
	}

	@Column(name = "id_equipament", nullable = false)
	public String getIdEquipament() {
		return this.idEquipament;
	}

	public void setIdEquipament(String idEquipament) {
		this.idEquipament = idEquipament;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "length", precision = 22, scale = 0)
	public Double getLength() {
		return this.length;
	}

	public void setLength(Double length) {
		this.length = length;
	}

	@Column(name = "height", precision = 22, scale = 0)
	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	@Column(name = "width", precision = 22, scale = 0)
	public Double getWidth() {
		return this.width;
	}

	public void setWidth(Double width) {
		this.width = width;
	}

	@Column(name = "part_per_hour", precision = 22, scale = 0)
	public Double getPartPerHour() {
		return this.partPerHour;
	}

	public void setPartPerHour(Double partPerHour) {
		this.partPerHour = partPerHour;
	}

	@Column(name = "utilidade")
	public String getUtilidade() {
		return this.utilidade;
	}

	public void setUtilidade(String utilidade) {
		this.utilidade = utilidade;
	}

	@Column(name = "cycle")
	public Integer getCycle() {
		return this.cycle;
	}

	public void setCycle(Integer cycle) {
		this.cycle = cycle;
	}

	@Column(name = "area_stack", precision = 22, scale = 0)
	public Double getAreaStack() {
		return this.areaStack;
	}

	public void setAreaStack(Double areaStack) {
		this.areaStack = areaStack;
	}

	@Column(name = "area", precision = 22, scale = 0)
	public Double getArea() {
		return this.area;
	}

	public void setArea(Double area) {
		this.area = area;
	}

	@Column(name = "max_stack")
	public Integer getMaxStack() {
		return this.maxStack;
	}

	public void setMaxStack(Integer maxStack) {
		this.maxStack = maxStack;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ferramenta")
	public Set<ParticipanteFerramenta> getParticipanteFerramentas() {
		return this.participanteFerramentas;
	}

	public void setParticipanteFerramentas(
			Set<ParticipanteFerramenta> participanteFerramentas) {
		this.participanteFerramentas = participanteFerramentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ferramenta")
	public Set<Montagem> getMontagems() {
		return this.montagems;
	}

	public void setMontagems(Set<Montagem> montagems) {
		this.montagems = montagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ferramenta")
	public Set<CompraFerramenta> getCompraFerramentas() {
		return this.compraFerramentas;
	}

	public void setCompraFerramentas(Set<CompraFerramenta> compraFerramentas) {
		this.compraFerramentas = compraFerramentas;
	}

}
