package br.com.synergy.model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FornecimentoFerramenta generated by hbm2java
 */
@Entity
@Table(name = "fornecimento_ferramenta", catalog = "sistema_gestao")
public class FornecimentoFerramenta implements java.io.Serializable {

	private FornecimentoFerramentaId id;
	private CotacaoFerramenta cotacaoFerramenta;
	private Boolean okPrazo;
	private Boolean okEspec;
	private Boolean okVisita;
	private Boolean okAssist;
	private Date data;
	private String pep;

	public FornecimentoFerramenta() {
	}

	public FornecimentoFerramenta(FornecimentoFerramentaId id,
			CotacaoFerramenta cotacaoFerramenta) {
		this.id = id;
		this.cotacaoFerramenta = cotacaoFerramenta;
	}

	public FornecimentoFerramenta(FornecimentoFerramentaId id,
			CotacaoFerramenta cotacaoFerramenta, Boolean okPrazo,
			Boolean okEspec, Boolean okVisita, Boolean okAssist, Date data,
			String pep) {
		this.id = id;
		this.cotacaoFerramenta = cotacaoFerramenta;
		this.okPrazo = okPrazo;
		this.okEspec = okEspec;
		this.okVisita = okVisita;
		this.okAssist = okAssist;
		this.data = data;
		this.pep = pep;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idfornecimentoFerramenta", column = @Column(name = "idfornecimento_ferramenta", nullable = false)),
			@AttributeOverride(name = "cotacaoFerramentaIdcotacao", column = @Column(name = "cotacao_ferramenta_idcotacao", nullable = false)) })
	public FornecimentoFerramentaId getId() {
		return this.id;
	}

	public void setId(FornecimentoFerramentaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotacao_ferramenta_idcotacao", nullable = false, insertable = false, updatable = false)
	public CotacaoFerramenta getCotacaoFerramenta() {
		return this.cotacaoFerramenta;
	}

	public void setCotacaoFerramenta(CotacaoFerramenta cotacaoFerramenta) {
		this.cotacaoFerramenta = cotacaoFerramenta;
	}

	@Column(name = "ok_prazo")
	public Boolean getOkPrazo() {
		return this.okPrazo;
	}

	public void setOkPrazo(Boolean okPrazo) {
		this.okPrazo = okPrazo;
	}

	@Column(name = "ok_espec")
	public Boolean getOkEspec() {
		return this.okEspec;
	}

	public void setOkEspec(Boolean okEspec) {
		this.okEspec = okEspec;
	}

	@Column(name = "ok_visita")
	public Boolean getOkVisita() {
		return this.okVisita;
	}

	public void setOkVisita(Boolean okVisita) {
		this.okVisita = okVisita;
	}

	@Column(name = "ok_assist")
	public Boolean getOkAssist() {
		return this.okAssist;
	}

	public void setOkAssist(Boolean okAssist) {
		this.okAssist = okAssist;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "pep")
	public String getPep() {
		return this.pep;
	}

	public void setPep(String pep) {
		this.pep = pep;
	}

}
