package br.com.synergy.model;

// Generated 25/07/2015 13:37:07 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FornecimentoPeca generated by hbm2java
 */
@Entity
@Table(name = "fornecimento_peca", catalog = "sistema_gestao")
public class FornecimentoPeca implements java.io.Serializable {

	private Long idfornecimentoPeca;
	private CotacaoPeca cotacaoPeca;
	private Pep pep;
	private Boolean okPrazo;
	private Boolean okEspec;
	private Boolean okVisita;
	private Boolean okAssist;
	private Date data;

	public FornecimentoPeca() {
	}

	public FornecimentoPeca(CotacaoPeca cotacaoPeca, Pep pep) {
		this.cotacaoPeca = cotacaoPeca;
		this.pep = pep;
	}

	public FornecimentoPeca(CotacaoPeca cotacaoPeca, Pep pep, Boolean okPrazo,
			Boolean okEspec, Boolean okVisita, Boolean okAssist, Date data) {
		this.cotacaoPeca = cotacaoPeca;
		this.pep = pep;
		this.okPrazo = okPrazo;
		this.okEspec = okEspec;
		this.okVisita = okVisita;
		this.okAssist = okAssist;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idfornecimento_peca", unique = true, nullable = false)
	public Long getIdfornecimentoPeca() {
		return this.idfornecimentoPeca;
	}

	public void setIdfornecimentoPeca(Long idfornecimentoPeca) {
		this.idfornecimentoPeca = idfornecimentoPeca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotacao_peca_idcotacao", nullable = false)
	public CotacaoPeca getCotacaoPeca() {
		return this.cotacaoPeca;
	}

	public void setCotacaoPeca(CotacaoPeca cotacaoPeca) {
		this.cotacaoPeca = cotacaoPeca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "pep_idpep", referencedColumnName = "idpep", nullable = false),
			@JoinColumn(name = "pep_Conta_idConta", referencedColumnName = "Conta_idConta", nullable = false) })
	public Pep getPep() {
		return this.pep;
	}

	public void setPep(Pep pep) {
		this.pep = pep;
	}

	@Column(name = "ok_prazo")
	public Boolean getOkPrazo() {
		return this.okPrazo;
	}

	public void setOkPrazo(Boolean okPrazo) {
		this.okPrazo = okPrazo;
	}

	@Column(name = "ok_espec")
	public Boolean getOkEspec() {
		return this.okEspec;
	}

	public void setOkEspec(Boolean okEspec) {
		this.okEspec = okEspec;
	}

	@Column(name = "ok_visita")
	public Boolean getOkVisita() {
		return this.okVisita;
	}

	public void setOkVisita(Boolean okVisita) {
		this.okVisita = okVisita;
	}

	@Column(name = "ok_assist")
	public Boolean getOkAssist() {
		return this.okAssist;
	}

	public void setOkAssist(Boolean okAssist) {
		this.okAssist = okAssist;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
