package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "sistema_gestao")
public class Material implements java.io.Serializable {

	private Long idmaterial;
	private String materialEspc;
	private String material;
	private String desc;
	private Boolean disponibilidade;
	private Set<ParticipanteMaterial> participanteMaterials = new HashSet<ParticipanteMaterial>(
			0);
	private Set<CompraMaterial> compraMaterials = new HashSet<CompraMaterial>(0);
	private Set<Peca> pecas = new HashSet<Peca>(0);

	public Material() {
	}

	public Material(String materialEspc) {
		this.materialEspc = materialEspc;
	}

	public Material(String materialEspc, String material, String desc,
			Boolean disponibilidade,
			Set<ParticipanteMaterial> participanteMaterials,
			Set<CompraMaterial> compraMaterials, Set<Peca> pecas) {
		this.materialEspc = materialEspc;
		this.material = material;
		this.desc = desc;
		this.disponibilidade = disponibilidade;
		this.participanteMaterials = participanteMaterials;
		this.compraMaterials = compraMaterials;
		this.pecas = pecas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmaterial", unique = true, nullable = false)
	public Long getIdmaterial() {
		return this.idmaterial;
	}

	public void setIdmaterial(Long idmaterial) {
		this.idmaterial = idmaterial;
	}

	@Column(name = "material_espc", nullable = false)
	public String getMaterialEspc() {
		return this.materialEspc;
	}

	public void setMaterialEspc(String materialEspc) {
		this.materialEspc = materialEspc;
	}

	@Column(name = "material")
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "desc")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "disponibilidade")
	public Boolean getDisponibilidade() {
		return this.disponibilidade;
	}

	public void setDisponibilidade(Boolean disponibilidade) {
		this.disponibilidade = disponibilidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<ParticipanteMaterial> getParticipanteMaterials() {
		return this.participanteMaterials;
	}

	public void setParticipanteMaterials(
			Set<ParticipanteMaterial> participanteMaterials) {
		this.participanteMaterials = participanteMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<CompraMaterial> getCompraMaterials() {
		return this.compraMaterials;
	}

	public void setCompraMaterials(Set<CompraMaterial> compraMaterials) {
		this.compraMaterials = compraMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<Peca> getPecas() {
		return this.pecas;
	}

	public void setPecas(Set<Peca> pecas) {
		this.pecas = pecas;
	}

}
