package br.com.synergy.model;

// Generated 25/07/2015 13:37:07 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "sistema_gestao")
public class Material implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idmaterial;
	private CotacaoMaterial cotacaoMaterial;
	private String materialEspc;
	private String material;
	private String desc;
	private Set<Peca> pecas = new HashSet<Peca>(0);

	public Material() {
	}

	public Material(CotacaoMaterial cotacaoMaterial, String materialEspc) {
		this.cotacaoMaterial = cotacaoMaterial;
		this.materialEspc = materialEspc;
	}

	public Material(CotacaoMaterial cotacaoMaterial, String materialEspc,
			String material, String desc, Set<Peca> pecas) {
		this.cotacaoMaterial = cotacaoMaterial;
		this.materialEspc = materialEspc;
		this.material = material;
		this.desc = desc;
		this.pecas = pecas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmaterial", unique = true, nullable = false)
	public Long getIdmaterial() {
		return this.idmaterial;
	}

	public void setIdmaterial(Long idmaterial) {
		this.idmaterial = idmaterial;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cotacao_material_idcotacao", nullable = false)
	public CotacaoMaterial getCotacaoMaterial() {
		return this.cotacaoMaterial;
	}

	public void setCotacaoMaterial(CotacaoMaterial cotacaoMaterial) {
		this.cotacaoMaterial = cotacaoMaterial;
	}

	@Column(name = "material_espc", nullable = false)
	public String getMaterialEspc() {
		return this.materialEspc;
	}

	public void setMaterialEspc(String materialEspc) {
		this.materialEspc = materialEspc;
	}
	@NotEmpty
	@Column(name = "material")
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "descricao")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<Peca> getPecas() {
		return this.pecas;
	}

	public void setPecas(Set<Peca> pecas) {
		this.pecas = pecas;
	}

}
