package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Montagem generated by hbm2java
 */
@Entity
@Table(name = "montagem", catalog = "sistema_gestao")
public class Montagem implements java.io.Serializable {

	private Long idmontagem;
	private Ferramenta ferramenta;
	private Peca peca;
	private Set<Conjunto> conjuntos = new HashSet<Conjunto>(0);

	public Montagem() {
	}

	public Montagem(Ferramenta ferramenta, Peca peca) {
		this.ferramenta = ferramenta;
		this.peca = peca;
	}

	public Montagem(Ferramenta ferramenta, Peca peca, Set<Conjunto> conjuntos) {
		this.ferramenta = ferramenta;
		this.peca = peca;
		this.conjuntos = conjuntos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmontagem", unique = true, nullable = false)
	public Long getIdmontagem() {
		return this.idmontagem;
	}

	public void setIdmontagem(Long idmontagem) {
		this.idmontagem = idmontagem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ferramenta_idferramenta", nullable = false)
	public Ferramenta getFerramenta() {
		return this.ferramenta;
	}

	public void setFerramenta(Ferramenta ferramenta) {
		this.ferramenta = ferramenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_idpeca", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "montagem")
	public Set<Conjunto> getConjuntos() {
		return this.conjuntos;
	}

	public void setConjuntos(Set<Conjunto> conjuntos) {
		this.conjuntos = conjuntos;
	}

}
