package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParticipanteFerramenta generated by hbm2java
 */
@Entity
@Table(name = "participante_ferramenta", catalog = "sistema_gestao")
public class ParticipanteFerramenta implements java.io.Serializable {

	private long idparticipanteFerramenta;
	private Ferramenta ferramenta;
	private Fornecedor fornecedor;
	private Set<CotacaoFerramenta> cotacaoFerramentas = new HashSet<CotacaoFerramenta>(
			0);

	public ParticipanteFerramenta() {
	}

	public ParticipanteFerramenta(long idparticipanteFerramenta,
			Ferramenta ferramenta, Fornecedor fornecedor) {
		this.idparticipanteFerramenta = idparticipanteFerramenta;
		this.ferramenta = ferramenta;
		this.fornecedor = fornecedor;
	}

	public ParticipanteFerramenta(long idparticipanteFerramenta,
			Ferramenta ferramenta, Fornecedor fornecedor,
			Set<CotacaoFerramenta> cotacaoFerramentas) {
		this.idparticipanteFerramenta = idparticipanteFerramenta;
		this.ferramenta = ferramenta;
		this.fornecedor = fornecedor;
		this.cotacaoFerramentas = cotacaoFerramentas;
	}

	@Id
	@Column(name = "idparticipante_ferramenta", unique = true, nullable = false)
	public long getIdparticipanteFerramenta() {
		return this.idparticipanteFerramenta;
	}

	public void setIdparticipanteFerramenta(long idparticipanteFerramenta) {
		this.idparticipanteFerramenta = idparticipanteFerramenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ferramenta_idferramenta", nullable = false)
	public Ferramenta getFerramenta() {
		return this.ferramenta;
	}

	public void setFerramenta(Ferramenta ferramenta) {
		this.ferramenta = ferramenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fornecedor_idfornecedor", nullable = false)
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participanteFerramenta")
	public Set<CotacaoFerramenta> getCotacaoFerramentas() {
		return this.cotacaoFerramentas;
	}

	public void setCotacaoFerramentas(Set<CotacaoFerramenta> cotacaoFerramentas) {
		this.cotacaoFerramentas = cotacaoFerramentas;
	}

}
