package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParticipanteMaterial generated by hbm2java
 */
@Entity
@Table(name = "participante_material", catalog = "sistema_gestao")
public class ParticipanteMaterial implements java.io.Serializable {

	private long idparticipante;
	private Fornecedor fornecedor;
	private Material material;
	private Set<CotacaoMaterial> cotacaoMaterials = new HashSet<CotacaoMaterial>(
			0);

	public ParticipanteMaterial() {
	}

	public ParticipanteMaterial(long idparticipante, Fornecedor fornecedor,
			Material material) {
		this.idparticipante = idparticipante;
		this.fornecedor = fornecedor;
		this.material = material;
	}

	public ParticipanteMaterial(long idparticipante, Fornecedor fornecedor,
			Material material, Set<CotacaoMaterial> cotacaoMaterials) {
		this.idparticipante = idparticipante;
		this.fornecedor = fornecedor;
		this.material = material;
		this.cotacaoMaterials = cotacaoMaterials;
	}

	@Id
	@Column(name = "idparticipante", unique = true, nullable = false)
	public long getIdparticipante() {
		return this.idparticipante;
	}

	public void setIdparticipante(long idparticipante) {
		this.idparticipante = idparticipante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fornecedor_idfornecedor", nullable = false)
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "material_idmaterial", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participanteMaterial")
	public Set<CotacaoMaterial> getCotacaoMaterials() {
		return this.cotacaoMaterials;
	}

	public void setCotacaoMaterials(Set<CotacaoMaterial> cotacaoMaterials) {
		this.cotacaoMaterials = cotacaoMaterials;
	}

}
