package br.com.synergy.model;

// Generated 05/08/2015 21:41:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParticipantePeca generated by hbm2java
 */
@Entity
@Table(name = "participante_peca", catalog = "sistema_gestao")
public class ParticipantePeca implements java.io.Serializable {

	private long idparticipantePeca;
	private Peca peca;
	private Fornecedor fornecedor;
	private Set<CotacaoPeca> cotacaoPecas = new HashSet<CotacaoPeca>(0);

	public ParticipantePeca() {
	}

	public ParticipantePeca(long idparticipantePeca, Peca peca,
			Fornecedor fornecedor) {
		this.idparticipantePeca = idparticipantePeca;
		this.peca = peca;
		this.fornecedor = fornecedor;
	}

	public ParticipantePeca(long idparticipantePeca, Peca peca,
			Fornecedor fornecedor, Set<CotacaoPeca> cotacaoPecas) {
		this.idparticipantePeca = idparticipantePeca;
		this.peca = peca;
		this.fornecedor = fornecedor;
		this.cotacaoPecas = cotacaoPecas;
	}

	@Id
	@Column(name = "idparticipante_peca", unique = true, nullable = false)
	public long getIdparticipantePeca() {
		return this.idparticipantePeca;
	}

	public void setIdparticipantePeca(long idparticipantePeca) {
		this.idparticipantePeca = idparticipantePeca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_idpeca", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fornecedor_idfornecedor", nullable = false)
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participantePeca")
	public Set<CotacaoPeca> getCotacaoPecas() {
		return this.cotacaoPecas;
	}

	public void setCotacaoPecas(Set<CotacaoPeca> cotacaoPecas) {
		this.cotacaoPecas = cotacaoPecas;
	}

}
