package br.com.synergy.model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Peca generated by hbm2java
 */
@Entity
@Table(name = "peca", catalog = "sistema_gestao")
public class Peca implements java.io.Serializable {

	private PecaId id;
	private Material material;
	private String pnLess;
	private String partName;
	private String desc;
	private String upcFna;
	private Set<Montagem> montagems = new HashSet<Montagem>(0);
	private Set<CotacaoPeca> cotacaoPecas = new HashSet<CotacaoPeca>(0);

	public Peca() {
	}

	public Peca(PecaId id, Material material) {
		this.id = id;
		this.material = material;
	}

	public Peca(PecaId id, Material material, String pnLess, String partName,
			String desc, String upcFna, Set<Montagem> montagems,
			Set<CotacaoPeca> cotacaoPecas) {
		this.id = id;
		this.material = material;
		this.pnLess = pnLess;
		this.partName = partName;
		this.desc = desc;
		this.upcFna = upcFna;
		this.montagems = montagems;
		this.cotacaoPecas = cotacaoPecas;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idpeca", column = @Column(name = "idpeca", nullable = false)),
			@AttributeOverride(name = "materialIdmaterial", column = @Column(name = "material_idmaterial", nullable = false)),
			@AttributeOverride(name = "materialCotacaoMaterialIdcotacao", column = @Column(name = "material_cotacao_material_idcotacao", nullable = false)) })
	public PecaId getId() {
		return this.id;
	}

	public void setId(PecaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "material_idmaterial", referencedColumnName = "idmaterial", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "material_cotacao_material_idcotacao", referencedColumnName = "cotacao_material_idcotacao", nullable = false, insertable = false, updatable = false) })
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Column(name = "pn_less")
	public String getPnLess() {
		return this.pnLess;
	}

	public void setPnLess(String pnLess) {
		this.pnLess = pnLess;
	}

	@Column(name = "part_name")
	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	@Column(name = "desc")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "upc_fna")
	public String getUpcFna() {
		return this.upcFna;
	}

	public void setUpcFna(String upcFna) {
		this.upcFna = upcFna;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "montagem_has_peca", catalog = "sistema_gestao", joinColumns = {
			@JoinColumn(name = "peca_idpeca", nullable = false, updatable = false),
			@JoinColumn(name = "peca_material_idmaterial", nullable = false, updatable = false),
			@JoinColumn(name = "peca_material_cotacao_material_idcotacao", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "montagem_idmontagem", nullable = false, updatable = false),
			@JoinColumn(name = "montagem_conjunto_idconjunto", nullable = false, updatable = false)})
	public Set<Montagem> getMontagems() {
		return this.montagems;
	}

	public void setMontagems(Set<Montagem> montagems) {
		this.montagems = montagems;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "cotacao_peca_has_peca", catalog = "sistema_gestao", joinColumns = {
			@JoinColumn(name = "peca_idpeca", nullable = false, updatable = false),
			@JoinColumn(name = "peca_material_idmaterial", nullable = false, updatable = false),
			@JoinColumn(name = "peca_material_cotacao_material_idcotacao", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cotacao_peca_idcotacao", nullable = false, updatable = false) })
	public Set<CotacaoPeca> getCotacaoPecas() {
		return this.cotacaoPecas;
	}

	public void setCotacaoPecas(Set<CotacaoPeca> cotacaoPecas) {
		this.cotacaoPecas = cotacaoPecas;
	}

}
