package br.com.synergy.model;

// Generated 25/07/2015 13:37:07 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pep generated by hbm2java
 */
@Entity
@Table(name = "pep", catalog = "sistema_gestao")
public class Pep implements java.io.Serializable {

	private PepId id;
	private Conta conta;
	private String numero;
	private Set<FornecimentoFerramenta> fornecimentoFerramentas = new HashSet<FornecimentoFerramenta>(
			0);
	private Set<FornecimentoPeca> fornecimentoPecas = new HashSet<FornecimentoPeca>(
			0);
	private Set<FornecimentoMaterial> fornecimentoMaterials = new HashSet<FornecimentoMaterial>(
			0);

	public Pep() {
	}

	public Pep(PepId id, Conta conta) {
		this.id = id;
		this.conta = conta;
	}

	public Pep(PepId id, Conta conta, String numero,
			Set<FornecimentoFerramenta> fornecimentoFerramentas,
			Set<FornecimentoPeca> fornecimentoPecas,
			Set<FornecimentoMaterial> fornecimentoMaterials) {
		this.id = id;
		this.conta = conta;
		this.numero = numero;
		this.fornecimentoFerramentas = fornecimentoFerramentas;
		this.fornecimentoPecas = fornecimentoPecas;
		this.fornecimentoMaterials = fornecimentoMaterials;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idpep", column = @Column(name = "idpep", nullable = false)),
			@AttributeOverride(name = "contaIdConta", column = @Column(name = "Conta_idConta", nullable = false)) })
	public PepId getId() {
		return this.id;
	}

	public void setId(PepId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Conta_idConta", nullable = false, insertable = false, updatable = false)
	public Conta getConta() {
		return this.conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	@Column(name = "numero", length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pep")
	public Set<FornecimentoFerramenta> getFornecimentoFerramentas() {
		return this.fornecimentoFerramentas;
	}

	public void setFornecimentoFerramentas(
			Set<FornecimentoFerramenta> fornecimentoFerramentas) {
		this.fornecimentoFerramentas = fornecimentoFerramentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pep")
	public Set<FornecimentoPeca> getFornecimentoPecas() {
		return this.fornecimentoPecas;
	}

	public void setFornecimentoPecas(Set<FornecimentoPeca> fornecimentoPecas) {
		this.fornecimentoPecas = fornecimentoPecas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pep")
	public Set<FornecimentoMaterial> getFornecimentoMaterials() {
		return this.fornecimentoMaterials;
	}

	public void setFornecimentoMaterials(
			Set<FornecimentoMaterial> fornecimentoMaterials) {
		this.fornecimentoMaterials = fornecimentoMaterials;
	}

}
