package br.com.synergy.model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PfmeaId generated by hbm2java
 */
@Embeddable
public class PfmeaId implements java.io.Serializable {

	private int idPfmea;
	private long riskAssesmentIdRiskAssesment;
	private long riskAssesmentConjuntoIdconjunto;

	public PfmeaId() {
	}

	public PfmeaId(int idPfmea, long riskAssesmentIdRiskAssesment,
			long riskAssesmentConjuntoIdconjunto) {
		this.idPfmea = idPfmea;
		this.riskAssesmentIdRiskAssesment = riskAssesmentIdRiskAssesment;
		this.riskAssesmentConjuntoIdconjunto = riskAssesmentConjuntoIdconjunto;
	}

	@Column(name = "id_pfmea", nullable = false)
	public int getIdPfmea() {
		return this.idPfmea;
	}

	public void setIdPfmea(int idPfmea) {
		this.idPfmea = idPfmea;
	}

	@Column(name = "risk_assesment_id_risk_assesment", nullable = false)
	public long getRiskAssesmentIdRiskAssesment() {
		return this.riskAssesmentIdRiskAssesment;
	}

	public void setRiskAssesmentIdRiskAssesment(
			long riskAssesmentIdRiskAssesment) {
		this.riskAssesmentIdRiskAssesment = riskAssesmentIdRiskAssesment;
	}

	@Column(name = "risk_assesment_conjunto_idconjunto", nullable = false)
	public long getRiskAssesmentConjuntoIdconjunto() {
		return this.riskAssesmentConjuntoIdconjunto;
	}

	public void setRiskAssesmentConjuntoIdconjunto(
			long riskAssesmentConjuntoIdconjunto) {
		this.riskAssesmentConjuntoIdconjunto = riskAssesmentConjuntoIdconjunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PfmeaId))
			return false;
		PfmeaId castOther = (PfmeaId) other;

		return (this.getIdPfmea() == castOther.getIdPfmea())
				&& (this.getRiskAssesmentIdRiskAssesment() == castOther
						.getRiskAssesmentIdRiskAssesment())
				&& (this.getRiskAssesmentConjuntoIdconjunto() == castOther
						.getRiskAssesmentConjuntoIdconjunto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPfmea();
		result = 37 * result + (int) this.getRiskAssesmentIdRiskAssesment();
		result = 37 * result + (int) this.getRiskAssesmentConjuntoIdconjunto();
		return result;
	}

}
