package br.com.synergy.model;

// Generated 23/07/2015 04:16:30 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RiskAssesmentId generated by hbm2java
 */
@Embeddable
public class RiskAssesmentId implements java.io.Serializable {

	private long idRiskAssesment;
	private long conjuntoIdconjunto;

	public RiskAssesmentId() {
	}

	public RiskAssesmentId(long idRiskAssesment, long conjuntoIdconjunto) {
		this.idRiskAssesment = idRiskAssesment;
		this.conjuntoIdconjunto = conjuntoIdconjunto;
	}

	@Column(name = "id_risk_assesment", nullable = false)
	public long getIdRiskAssesment() {
		return this.idRiskAssesment;
	}

	public void setIdRiskAssesment(long idRiskAssesment) {
		this.idRiskAssesment = idRiskAssesment;
	}

	@Column(name = "conjunto_idconjunto", nullable = false)
	public long getConjuntoIdconjunto() {
		return this.conjuntoIdconjunto;
	}

	public void setConjuntoIdconjunto(long conjuntoIdconjunto) {
		this.conjuntoIdconjunto = conjuntoIdconjunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RiskAssesmentId))
			return false;
		RiskAssesmentId castOther = (RiskAssesmentId) other;

		return (this.getIdRiskAssesment() == castOther.getIdRiskAssesment())
				&& (this.getConjuntoIdconjunto() == castOther
						.getConjuntoIdconjunto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdRiskAssesment();
		result = 37 * result + (int) this.getConjuntoIdconjunto();
		return result;
	}

}
